#! /bin/bash
export CLASSPATH=.:../j3d/lib_64/ext/j3dcore.jar:../j3d/lib_64/ext/j3dutils.jar:../j3d/lib_64/ext/vecmath.jar
export LD_LIBRARY_PATH=../j3d/lib_64/amd64
echo $LD_LIBRARY_PATH
cd source
java -splash:../images/splash.gif Pinito3D
